(* Generated by Lem from evm.lem. *)

Require Import Arith.
Require Import Bool.
Require Import List.
Require Import String.
Require Import Program.Wf.

Open Scope nat_scope.
Open Scope string_scope.


Lemmalog2_def_lemma:((forallx,(Z.eqb  
(if int_lteb x((Zpred (Zpos (P_of_succ_nat 1)))) then(Zpred (Zpos (P_of_succ_nat 0)))
  else Coq.ZArith.BinInt.Zplus((Zpred (Zpos (P_of_succ_nat 1)))) (Z.log2 ( Coq.ZArith.Zdiv.Zdiv x((Zpred (Zpos (P_of_succ_nat 2))))))) 
  (Z.log2 x) : Prop)): Prop) .
