(*Generated by Lem from julia.lem.*)

(* Specification of Solidity intermediate language *)

open Lem_pervasives
open Lem_list
open Lem_string
open Lem_word
open Word256
open Word160
open Word8

(** Syntax *)

type id = Nat_big_num.num

type builtin_type =
 | Boolean
 | S256
 | S128
 | S64
 | S32
 | S8
 | U256
 | U128
 | U64
 | U32
 | U8

type type_name =
 | BuiltinType of builtin_type
 | CustomType of id

type literal_kind =
 | TrueLiteral
 | FalseLiteral
 | StringLiteral of word8 list
 | NumberLiteral of Nat_big_num.num

type expression =
 | FunctionCall of id * expression list
 | Identifier of id
 | Literal of literal_kind * type_name

type statement =
 | Block of statement list
 | FunctionDefinition of id * (id * type_name) list * (id * type_name) list * statement list
 | VariableDeclaration of (id * type_name) list * expression
 | Assignment of id list * expression
 | Switch of expression * (literal_kind * type_name * statement list) list *  ( statement list)option
 | Break
 | Continue
 | ForLoop of statement list * expression * statement list * statement list

(** Interpreter *)


