chapter {* Generated by Lem from julia.lem. *}

theory "JuliaAuxiliary" 

imports 
 	 Main "~~/src/HOL/Library/Code_Target_Numeral"
	 "Lem_pervasives" 
	 "Lem_list" 
	 "Lem_map" 
	 "Lem_string" 
	 "Lem_word" 
	 "/mnt/c/Users/mrsmk/Desktop/eth-isabelle/lem/Word256" 
	 "/mnt/c/Users/mrsmk/Desktop/eth-isabelle/lem/Word160" 
	 "/mnt/c/Users/mrsmk/Desktop/eth-isabelle/lem/Word8" 
	 "Julia" 

begin 


(****************************************************)
(*                                                  *)
(* Termination Proofs                               *)
(*                                                  *)
(****************************************************)

termination eval_statement by lexicographic_order



end
